# Generated by Django 4.2.7 on 2025-10-12 14:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icone', models.CharField(blank=True, help_text="Nome do ícone (ex: 'restaurant', 'store')", max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Estabelecimento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=300)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('cnpj', models.CharField(blank=True, max_length=18, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: XX.XXX.XXX/XXXX-XX', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('proprietario', models.CharField(blank=True, max_length=200, verbose_name='Proprietário')),
                ('horario_funcionamento', models.TextField(blank=True, verbose_name='Horário de Funcionamento')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='estabelecimentos/')),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False, verbose_name='Estabelecimento em destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estabelecimentos', to='core.categoria')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estabelecimentos_criados', to=settings.AUTH_USER_MODEL)),
                ('favoritos', models.ManyToManyField(blank=True, related_name='estabelecimentos_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('is_dev', models.BooleanField(default=False, verbose_name='É desenvolvedor/admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='FotoEstabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='estabelecimentos/fotos/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.estabelecimento')),
            ],
            options={
                'verbose_name': 'Foto do Estabelecimento',
                'verbose_name_plural': 'Fotos dos Estabelecimentos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('tipo', models.CharField(choices=[('gastronomia', 'Gastronomia'), ('moda', 'Moda'), ('cultura', 'Cultura'), ('esporte', 'Esporte'), ('educacao', 'Educação'), ('tecnologia', 'Tecnologia'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('localizacao', models.CharField(max_length=300, verbose_name='Localização')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora de Término')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False, verbose_name='Evento em destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.estabelecimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-criado_em'],
                'unique_together': {('estabelecimento', 'usuario')},
            },
        ),
    ]
